### ISSUE TITLE
Make bin fails

### ISSUE THREAD

**Issue by vesameskanen** [whosonfirst/go-whosonfirst-clone#10]
It seems that some recent changes have broken the clone tool. The install steps of README.md give an error message when make bin is run:

src/github.com/whosonfirst/go-whosonfirst-clone/clone.go:125: cannot use abs_path (type string) as type io.Reader in argument to "github.com/whosonfirst/go-whosonfirst-csv".NewDict:
        string does not implement io.Reader (missing Read method)

**Comment by thisisaaronland** [comment]
Oh, oops. Those changes happened on Tuesday. I will fix the underlying
issue and look in to "vendoring" dependencies for the future...

**Comment by thisisaaronland** [comment]
Fixed. Apologies for the bad craziness...

**Comment by vesameskanen** [comment]
Thank you! That was a quick  fix .)

**Comment by thisisaaronland** [comment]
There is a `vendor` branch which _should_ work with all the dependencies bundled in place. Do you have a moment to try it out and confirm it works?

https://github.com/whosonfirst/go-whosonfirst-clone/tree/vendor

Where "should work" means you just type "make build" as usual :-)

Cheers,

**Comment by vesameskanen** [comment]
Hi @thisisaaronland, I tested the vendor branch with  'make build' and after that, running a custom data cloning script for finnish data. Everything seemed to work fine.

**Comment by thisisaaronland** [comment]
Thanks!
