### ISSUE TITLE
Server error replaces file contents with XML error response

### ISSUE THREAD

**Issue by stephenkhess** [whosonfirst/go-whosonfirst-clone#6]
I tried running the utility but it appears that when the server returns an error, XML is dropped into the geojson file:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><RequestId>869BD31C5B34FB96</RequestId><HostId>a4U+mbECCoUshCCDsl94BQXPsQfR6N/rW0PtscnjerPU3nGzsv4nNPCFwEtkydy+fNPghHOxvKE=</HostId></Error>%
```

**Comment by thisisaaronland** [comment]
Beauty...

**Comment by thisisaaronland** [comment]
Oh there's the problem:

https://github.com/whosonfirst/go-whosonfirst-clone/blob/master/clone.go#L271-L279

I guess I just got used to Python freaking out and blowing its brains out when it encounters a not-200 status code. I will update accordingly...
